BEGIN;

INSERT INTO equipos (
  id_equipo, marca, modelo, categoria, pais_marca, pais_fabricacion,
  descripcion, anio_modelo, publicado
) VALUES
(
  'GNSS-LEICA-GS10', 'Leica', 'Viva GS10', 'GNSS', 'Suiza', 'Suiza',
  'Receptor GNSS modular para estaciones base y rover con antena externa, registro RINEX y enlaces de datos externos.',
  2015, TRUE
),
(
  'GNSS-LEICA-GS25', 'Leica', 'Viva GS25', 'GNSS', 'Suiza', 'Suiza',
  'Receptor GNSS profesional con radio UHF y módem 3.5G integrados para estaciones base, rover y monitoreo.',
  2016, TRUE
)
ON CONFLICT (id_equipo) DO UPDATE SET
  marca=EXCLUDED.marca,
  modelo=EXCLUDED.modelo,
  categoria=EXCLUDED.categoria,
  pais_marca=EXCLUDED.pais_marca,
  pais_fabricacion=EXCLUDED.pais_fabricacion,
  descripcion=EXCLUDED.descripcion,
  anio_modelo=EXCLUDED.anio_modelo,
  publicado=EXCLUDED.publicado;

INSERT INTO base_evaluacion (
  id_equipo, tiene_imu, tiene_camara, canales_gnss, memoria, sim_4g,
  laser, bateria_intercambiable, bateria_caliente, radio_frecuencia,
  constelaciones, autonomia_bateria, peso_max, tiempo_inicializacion,
  rtk_horizontal_mm, rtk_vertical_mm, rtk_ppm_h, rtk_ppm_v,
  static_horizontal_mm, static_vertical_mm, static_ppm_h, static_ppm_v,
  largo_mm, ancho_mm, alto_mm, gps, glonass, galileo, beidou, qzss,
  navic_irnss, sbas, tiene_ppp, ppp_h_cm, cantidad_camaras,
  temperatura_operacion_min_c, temperatura_operacion_max_c,
  temperatura_almacenamiento_min_c, temperatura_almacenamiento_max_c,
  humedad_max_pct, caida_m, humedad_condicion, proteccion_ip,
  caida_condiciones, vibracion_norma, choque_condiciones,
  ambiental_notas, ambiental_fuente, memoria_expandible, bluetooth,
  wifi, uhf_tx_rx_integrada, lte_4g, radio_potencia_ajustable,
  protocolo_multimarca, bateria_interna, registro_rinex, registro_rinex_3,
  registro_propietario, radio_potencia_max_w, bluetooth_version,
  uhf_modo, radio_protocolos, tipo_bateria, formato_propietario,
  tecnica_notas, tecnica_fuente, cantidad_baterias, lemo,
  baterias_conectores_fuente, baterias_conectores_notas,
  red_rtk_horizontal_mm, red_rtk_vertical_mm, red_rtk_ppm_h,
  red_rtk_ppm_v, largo_static_horizontal_mm, largo_static_vertical_mm,
  largo_static_ppm_h, largo_static_ppm_v, inclinacion_imu_deg,
  actualizacion_hz, usb, usb_c, rs232, auditoria_fuente, auditoria_notas
) VALUES
(
  'GNSS-LEICA-GS10', FALSE, FALSE, 555, 8, FALSE,
  FALSE, TRUE, NULL, 'Enlaces externos UHF/VHF mediante módem Leica GFU',
  6, 15, 1200, 4,
  8, 15, 1, 1,
  3, 5, 0.5, 0.5,
  212, 166, 79, TRUE, TRUE, TRUE, TRUE, TRUE,
  TRUE, TRUE, TRUE, 3, 0,
  -40, 65, -40, 80,
  100, 2, '100% conforme a ISO 9022 y MIL-STD-810G', 'IP68',
  'Vuelco desde jalón de 2 m sobre superficie dura',
  'ISO 9022-36-08 / MIL-STD-810G 514.6 Cat.24',
  '40 g durante 15 a 23 ms; MIL-STD-810G 516.6 I',
  'Protección frente a agua, arena y polvo; módem externo Leica GFU con IP67.',
  'Leica_Viva_GS10_DS.pdf, página 2',
  TRUE, TRUE,
  FALSE, FALSE, FALSE, NULL,
  TRUE, TRUE, TRUE, NULL,
  TRUE, NULL, '2.00 + EDR, clase 2',
  'Módem UHF/VHF externo; hasta tres enlaces simultáneos',
  'Leica, Leica 4G, CMR, CMR+, RTCM 2.2, 2.3, 3.0, 3.1 y 3.2 MSM',
  '2 baterías Li-Ion intercambiables de 6 Ah / 7.4 V',
  'Leica GNSS raw data',
  'QZSS L6, NavIC L5, GLONASS L3, BeiDou B3 y Galileo E6 se declararon sujetos a actualización de firmware. SmartLink y algunas funciones dependen de la licencia.',
  'Leica_Viva_GS10_DS.pdf, páginas 1-2; ficha aportada por el usuario el 2026-09-29.',
  2, TRUE,
  'Leica_Viva_GS10_DS.pdf, página 2',
  'La ficha confirma dos baterías y conectores LEMO, pero no declara el número de pines.',
  8, 15, 0.5,
  0.5, 3, 3.5,
  0.1, 0.4, NULL,
  20, TRUE, FALSE, TRUE,
  'Leica_Viva_GS10_DS.pdf; páginas 1-2; auditoría 2026-09-29.',
  'Receptor modular sin antena GNSS integrada declarada. No se atribuyen IMU, cámara, Wi-Fi, LTE ni radio UHF integrada; los enlaces celulares y UHF/VHF son externos.'
),
(
  'GNSS-LEICA-GS25', FALSE, FALSE, 555, 8, FALSE,
  FALSE, TRUE, NULL, 'UHF integrada 403-470 MHz Tx/Rx; 1 W',
  6, 14, 1840, 4,
  8, 15, 1, 1,
  3, 5, 0.5, 0.5,
  220, 200, 94, TRUE, TRUE, TRUE, TRUE, TRUE,
  TRUE, TRUE, TRUE, 3, 0,
  -40, 65, -40, 80,
  100, 2, '100% conforme a ISO 9022 y MIL-STD-810G', 'IP68',
  'Vuelco desde jalón de 2 m sobre superficie dura',
  'ISO 9022-36-08 / MIL-STD-810G 514.6 Cat.24',
  '40 g durante 15 a 23 ms; MIL-STD-810G 516.6 I',
  'Protección frente a agua, arena y polvo. Módem celular integrado 3.5G, no LTE.',
  'Leica-Viva-GS25-DS.pdf, página 2',
  TRUE, TRUE,
  FALSE, TRUE, FALSE, NULL,
  TRUE, TRUE, TRUE, NULL,
  TRUE, 1, '2.00 + EDR, clase 2',
  'UHF integrada 403-470 MHz Tx/Rx con antena externa',
  'Leica, Leica 4G, CMR, CMR+, RTCM 2.2, 2.3, 3.0, 3.1 y 3.2 MSM',
  'Batería Li-Ion intercambiable de 5.8 Ah / 14.8 V',
  'Leica GNSS raw data',
  'QZSS, NavIC L5, GLONASS L3, BeiDou B3 y Galileo E6 se declararon sujetos a actualización de firmware. SmartLink, RINEX y frecuencias de salida dependen de la variante o licencia.',
  'Leica-Viva-GS25-DS.pdf, páginas 1-2; ficha aportada por el usuario el 2026-09-29.',
  NULL, TRUE,
  'Leica-Viva-GS25-DS.pdf, página 2',
  'La ficha confirma batería intercambiable y conectores LEMO, pero no declara cantidad de baterías ni número de pines.',
  8, 15, 0.5,
  0.5, 3, 3.5,
  0.1, 0.4, NULL,
  20, TRUE, FALSE, TRUE,
  'Leica-Viva-GS25-DS.pdf; páginas 1-2; auditoría 2026-09-29.',
  'Módem 3.5G y radio UHF integrados. No se atribuyen IMU, cámara, Wi-Fi ni LTE.'
)
ON CONFLICT (id_equipo) DO UPDATE SET
  tiene_imu=EXCLUDED.tiene_imu,
  tiene_camara=EXCLUDED.tiene_camara,
  canales_gnss=EXCLUDED.canales_gnss,
  memoria=EXCLUDED.memoria,
  sim_4g=EXCLUDED.sim_4g,
  laser=EXCLUDED.laser,
  bateria_intercambiable=EXCLUDED.bateria_intercambiable,
  bateria_caliente=EXCLUDED.bateria_caliente,
  radio_frecuencia=EXCLUDED.radio_frecuencia,
  constelaciones=EXCLUDED.constelaciones,
  autonomia_bateria=EXCLUDED.autonomia_bateria,
  peso_max=EXCLUDED.peso_max,
  tiempo_inicializacion=EXCLUDED.tiempo_inicializacion,
  rtk_horizontal_mm=EXCLUDED.rtk_horizontal_mm,
  rtk_vertical_mm=EXCLUDED.rtk_vertical_mm,
  rtk_ppm_h=EXCLUDED.rtk_ppm_h,
  rtk_ppm_v=EXCLUDED.rtk_ppm_v,
  static_horizontal_mm=EXCLUDED.static_horizontal_mm,
  static_vertical_mm=EXCLUDED.static_vertical_mm,
  static_ppm_h=EXCLUDED.static_ppm_h,
  static_ppm_v=EXCLUDED.static_ppm_v,
  largo_mm=EXCLUDED.largo_mm,
  ancho_mm=EXCLUDED.ancho_mm,
  alto_mm=EXCLUDED.alto_mm,
  gps=EXCLUDED.gps,
  glonass=EXCLUDED.glonass,
  galileo=EXCLUDED.galileo,
  beidou=EXCLUDED.beidou,
  qzss=EXCLUDED.qzss,
  navic_irnss=EXCLUDED.navic_irnss,
  sbas=EXCLUDED.sbas,
  tiene_ppp=EXCLUDED.tiene_ppp,
  ppp_h_cm=EXCLUDED.ppp_h_cm,
  cantidad_camaras=EXCLUDED.cantidad_camaras,
  temperatura_operacion_min_c=EXCLUDED.temperatura_operacion_min_c,
  temperatura_operacion_max_c=EXCLUDED.temperatura_operacion_max_c,
  temperatura_almacenamiento_min_c=EXCLUDED.temperatura_almacenamiento_min_c,
  temperatura_almacenamiento_max_c=EXCLUDED.temperatura_almacenamiento_max_c,
  humedad_max_pct=EXCLUDED.humedad_max_pct,
  caida_m=EXCLUDED.caida_m,
  humedad_condicion=EXCLUDED.humedad_condicion,
  proteccion_ip=EXCLUDED.proteccion_ip,
  caida_condiciones=EXCLUDED.caida_condiciones,
  vibracion_norma=EXCLUDED.vibracion_norma,
  choque_condiciones=EXCLUDED.choque_condiciones,
  ambiental_notas=EXCLUDED.ambiental_notas,
  ambiental_fuente=EXCLUDED.ambiental_fuente,
  memoria_expandible=EXCLUDED.memoria_expandible,
  bluetooth=EXCLUDED.bluetooth,
  wifi=EXCLUDED.wifi,
  uhf_tx_rx_integrada=EXCLUDED.uhf_tx_rx_integrada,
  lte_4g=EXCLUDED.lte_4g,
  radio_potencia_ajustable=EXCLUDED.radio_potencia_ajustable,
  protocolo_multimarca=EXCLUDED.protocolo_multimarca,
  bateria_interna=EXCLUDED.bateria_interna,
  registro_rinex=EXCLUDED.registro_rinex,
  registro_rinex_3=EXCLUDED.registro_rinex_3,
  registro_propietario=EXCLUDED.registro_propietario,
  radio_potencia_max_w=EXCLUDED.radio_potencia_max_w,
  bluetooth_version=EXCLUDED.bluetooth_version,
  uhf_modo=EXCLUDED.uhf_modo,
  radio_protocolos=EXCLUDED.radio_protocolos,
  tipo_bateria=EXCLUDED.tipo_bateria,
  formato_propietario=EXCLUDED.formato_propietario,
  tecnica_notas=EXCLUDED.tecnica_notas,
  tecnica_fuente=EXCLUDED.tecnica_fuente,
  cantidad_baterias=EXCLUDED.cantidad_baterias,
  lemo=EXCLUDED.lemo,
  baterias_conectores_fuente=EXCLUDED.baterias_conectores_fuente,
  baterias_conectores_notas=EXCLUDED.baterias_conectores_notas,
  red_rtk_horizontal_mm=EXCLUDED.red_rtk_horizontal_mm,
  red_rtk_vertical_mm=EXCLUDED.red_rtk_vertical_mm,
  red_rtk_ppm_h=EXCLUDED.red_rtk_ppm_h,
  red_rtk_ppm_v=EXCLUDED.red_rtk_ppm_v,
  largo_static_horizontal_mm=EXCLUDED.largo_static_horizontal_mm,
  largo_static_vertical_mm=EXCLUDED.largo_static_vertical_mm,
  largo_static_ppm_h=EXCLUDED.largo_static_ppm_h,
  largo_static_ppm_v=EXCLUDED.largo_static_ppm_v,
  inclinacion_imu_deg=EXCLUDED.inclinacion_imu_deg,
  actualizacion_hz=EXCLUDED.actualizacion_hz,
  usb=EXCLUDED.usb,
  usb_c=EXCLUDED.usb_c,
  rs232=EXCLUDED.rs232,
  auditoria_fuente=EXCLUDED.auditoria_fuente,
  auditoria_notas=EXCLUDED.auditoria_notas;

INSERT INTO equipo_radio_frecuencia (id_equipo, frecuencia_min_mhz, frecuencia_max_mhz)
VALUES ('GNSS-LEICA-GS25', 403, 470)
ON CONFLICT (id_equipo, frecuencia_min_mhz, frecuencia_max_mhz) DO NOTHING;

COMMIT;
