BEGIN;

INSERT INTO equipos (
  id_equipo, marca, modelo, categoria, pais_marca, pais_fabricacion,
  descripcion, anio_modelo, publicado
) VALUES (
  'GNSS-SINOGNSS-T20', 'SinoGNSS', 'T20 Palm RTK', 'GNSS', 'China', 'China',
  'Receptor GNSS RTK compacto de 1590 canales con IMU de 60 grados, radio UHF integrada y NFC.',
  2025, TRUE
)
ON CONFLICT (id_equipo) DO UPDATE SET
  marca=EXCLUDED.marca,
  modelo=EXCLUDED.modelo,
  categoria=EXCLUDED.categoria,
  pais_marca=EXCLUDED.pais_marca,
  pais_fabricacion=EXCLUDED.pais_fabricacion,
  descripcion=EXCLUDED.descripcion,
  anio_modelo=EXCLUDED.anio_modelo,
  publicado=EXCLUDED.publicado;

INSERT INTO base_evaluacion (
  id_equipo, tiene_imu, tiene_camara, canales_gnss, memoria, sim_4g,
  laser, bateria_intercambiable, bateria_caliente, mp_camara,
  radio_frecuencia, constelaciones, autonomia_bateria, peso_max,
  tiempo_inicializacion, rtk_horizontal_mm, rtk_vertical_mm, rtk_ppm_h,
  rtk_ppm_v, static_horizontal_mm, static_vertical_mm, static_ppm_h,
  static_ppm_v, largo_mm, ancho_mm, alto_mm, gps, glonass, galileo,
  beidou, qzss, navic_irnss, sbas, tiene_ppp, ppp_h_cm, ppp_v_cm,
  cantidad_camaras, tiene_snlonglink, temperatura_operacion_min_c,
  temperatura_operacion_max_c, temperatura_almacenamiento_min_c,
  temperatura_almacenamiento_max_c, humedad_max_pct, caida_m,
  humedad_condicion, proteccion_ip, caida_condiciones, vibracion_norma,
  choque_condiciones, ambiental_notas, ambiental_fuente,
  memoria_opcional_fabrica_max_gb, imu_generacion, imu_tecnologia,
  memoria_expandible, bluetooth, wifi, uhf_tx_rx_integrada, lte_4g,
  radio_potencia_ajustable, protocolo_multimarca, bateria_interna,
  registro_rinex, registro_rinex_3, registro_propietario,
  radio_potencia_max_w, bluetooth_version, uhf_modo, radio_protocolos,
  tipo_bateria, formato_propietario, tecnica_notas, tecnica_fuente,
  cantidad_baterias, lemo, baterias_conectores_fuente,
  baterias_conectores_notas, red_rtk_horizontal_mm,
  red_rtk_vertical_mm, red_rtk_ppm_h, red_rtk_ppm_v,
  largo_static_horizontal_mm, largo_static_vertical_mm,
  largo_static_ppm_h, largo_static_ppm_v, inclinacion_imu_deg,
  actualizacion_hz, usb, usb_c, rs232, auditoria_fuente,
  auditoria_notas
) VALUES (
  'GNSS-SINOGNSS-T20', TRUE, FALSE, 1590, 8, FALSE,
  FALSE, FALSE, FALSE, 0,
  'UHF integrada 410-470 MHz Tx/Rx; 0.5 W, 1 W o 2 W', 6, 20, 670,
  10, 8, 15, 1,
  1, 2.5, 5, 0.5,
  0.5, 149, 149, 48, TRUE, TRUE, TRUE,
  TRUE, TRUE, TRUE, TRUE, FALSE, NULL, NULL,
  0, TRUE, -30,
  65, -40,
  85, 100, 2,
  '100% sin condensación', 'IP67', 'Caída de 2 m sobre concreto', NULL,
  NULL, 'Carcasa de aleación de magnesio y aluminio; resistencia a caída declarada por el fabricante.',
  'SinoGNSS T20 Palm RTK_EN.pdf, página 1',
  32, 'Tercera generación', 'IMU integrada con compensación de inclinación sin dependencia del campo magnético',
  FALSE, TRUE, FALSE, TRUE, FALSE,
  TRUE, TRUE, TRUE,
  TRUE, NULL, TRUE,
  2, '5.0 dual mode', 'UHF integrada Tx/Rx',
  'Transparent, TT450S, South, Mac y SNLongLink',
  'Batería interna de litio de 10000 mAh; carga rápida QC2.0/QC3.0',
  'ComNav Binary',
  'La memoria estándar es 8 GB; 16 GB y 32 GB son opciones de fábrica al realizar el pedido, no expansión de usuario. La ficha declara tasas de datos de 1, 2, 5 y 10 Hz, y salida ComNav Binary de hasta 20 Hz. No declara cámara, láser, Wi-Fi, LTE ni precisión PPP.',
  'SinoGNSS T20 Palm RTK_EN.pdf, páginas 1-2; ficha aportada por el usuario el 2026-09-29.',
  1, FALSE,
  'SinoGNSS T20 Palm RTK_EN.pdf, página 1',
  'La batería es interna. La interfaz física declara USB Type-C, TNC para datalink y rosca 5/8 UNC; no declara conector LEMO.',
  NULL, NULL, NULL, NULL,
  3, 3.5,
  0.1, 0.4, 60,
  10, TRUE, TRUE, NULL,
  'SinoGNSS T20 Palm RTK_EN.pdf; páginas 1-2; auditoría 2026-09-29.',
  'RTK: 8 mm + 1 ppm horizontal y 15 mm + 1 ppm vertical. Estático/rápido: 2.5 mm + 0.5 ppm y 5 mm + 0.5 ppm. Estático prolongado: 3 mm + 0.1 ppm y 3.5 mm + 0.4 ppm. Inicialización RTK menor de 10 s; arranque en frío hasta 45 s. Alcance UHF de 3 a 15 km según el entorno.'
)
ON CONFLICT (id_equipo) DO UPDATE SET
  tiene_imu=EXCLUDED.tiene_imu,
  tiene_camara=EXCLUDED.tiene_camara,
  canales_gnss=EXCLUDED.canales_gnss,
  memoria=EXCLUDED.memoria,
  sim_4g=EXCLUDED.sim_4g,
  laser=EXCLUDED.laser,
  bateria_intercambiable=EXCLUDED.bateria_intercambiable,
  bateria_caliente=EXCLUDED.bateria_caliente,
  mp_camara=EXCLUDED.mp_camara,
  radio_frecuencia=EXCLUDED.radio_frecuencia,
  constelaciones=EXCLUDED.constelaciones,
  autonomia_bateria=EXCLUDED.autonomia_bateria,
  peso_max=EXCLUDED.peso_max,
  tiempo_inicializacion=EXCLUDED.tiempo_inicializacion,
  rtk_horizontal_mm=EXCLUDED.rtk_horizontal_mm,
  rtk_vertical_mm=EXCLUDED.rtk_vertical_mm,
  rtk_ppm_h=EXCLUDED.rtk_ppm_h,
  rtk_ppm_v=EXCLUDED.rtk_ppm_v,
  static_horizontal_mm=EXCLUDED.static_horizontal_mm,
  static_vertical_mm=EXCLUDED.static_vertical_mm,
  static_ppm_h=EXCLUDED.static_ppm_h,
  static_ppm_v=EXCLUDED.static_ppm_v,
  largo_mm=EXCLUDED.largo_mm,
  ancho_mm=EXCLUDED.ancho_mm,
  alto_mm=EXCLUDED.alto_mm,
  gps=EXCLUDED.gps,
  glonass=EXCLUDED.glonass,
  galileo=EXCLUDED.galileo,
  beidou=EXCLUDED.beidou,
  qzss=EXCLUDED.qzss,
  navic_irnss=EXCLUDED.navic_irnss,
  sbas=EXCLUDED.sbas,
  tiene_ppp=EXCLUDED.tiene_ppp,
  ppp_h_cm=EXCLUDED.ppp_h_cm,
  ppp_v_cm=EXCLUDED.ppp_v_cm,
  cantidad_camaras=EXCLUDED.cantidad_camaras,
  tiene_snlonglink=EXCLUDED.tiene_snlonglink,
  temperatura_operacion_min_c=EXCLUDED.temperatura_operacion_min_c,
  temperatura_operacion_max_c=EXCLUDED.temperatura_operacion_max_c,
  temperatura_almacenamiento_min_c=EXCLUDED.temperatura_almacenamiento_min_c,
  temperatura_almacenamiento_max_c=EXCLUDED.temperatura_almacenamiento_max_c,
  humedad_max_pct=EXCLUDED.humedad_max_pct,
  caida_m=EXCLUDED.caida_m,
  humedad_condicion=EXCLUDED.humedad_condicion,
  proteccion_ip=EXCLUDED.proteccion_ip,
  caida_condiciones=EXCLUDED.caida_condiciones,
  vibracion_norma=EXCLUDED.vibracion_norma,
  choque_condiciones=EXCLUDED.choque_condiciones,
  ambiental_notas=EXCLUDED.ambiental_notas,
  ambiental_fuente=EXCLUDED.ambiental_fuente,
  memoria_opcional_fabrica_max_gb=EXCLUDED.memoria_opcional_fabrica_max_gb,
  imu_generacion=EXCLUDED.imu_generacion,
  imu_tecnologia=EXCLUDED.imu_tecnologia,
  memoria_expandible=EXCLUDED.memoria_expandible,
  bluetooth=EXCLUDED.bluetooth,
  wifi=EXCLUDED.wifi,
  uhf_tx_rx_integrada=EXCLUDED.uhf_tx_rx_integrada,
  lte_4g=EXCLUDED.lte_4g,
  radio_potencia_ajustable=EXCLUDED.radio_potencia_ajustable,
  protocolo_multimarca=EXCLUDED.protocolo_multimarca,
  bateria_interna=EXCLUDED.bateria_interna,
  registro_rinex=EXCLUDED.registro_rinex,
  registro_rinex_3=EXCLUDED.registro_rinex_3,
  registro_propietario=EXCLUDED.registro_propietario,
  radio_potencia_max_w=EXCLUDED.radio_potencia_max_w,
  bluetooth_version=EXCLUDED.bluetooth_version,
  uhf_modo=EXCLUDED.uhf_modo,
  radio_protocolos=EXCLUDED.radio_protocolos,
  tipo_bateria=EXCLUDED.tipo_bateria,
  formato_propietario=EXCLUDED.formato_propietario,
  tecnica_notas=EXCLUDED.tecnica_notas,
  tecnica_fuente=EXCLUDED.tecnica_fuente,
  cantidad_baterias=EXCLUDED.cantidad_baterias,
  lemo=EXCLUDED.lemo,
  baterias_conectores_fuente=EXCLUDED.baterias_conectores_fuente,
  baterias_conectores_notas=EXCLUDED.baterias_conectores_notas,
  red_rtk_horizontal_mm=EXCLUDED.red_rtk_horizontal_mm,
  red_rtk_vertical_mm=EXCLUDED.red_rtk_vertical_mm,
  red_rtk_ppm_h=EXCLUDED.red_rtk_ppm_h,
  red_rtk_ppm_v=EXCLUDED.red_rtk_ppm_v,
  largo_static_horizontal_mm=EXCLUDED.largo_static_horizontal_mm,
  largo_static_vertical_mm=EXCLUDED.largo_static_vertical_mm,
  largo_static_ppm_h=EXCLUDED.largo_static_ppm_h,
  largo_static_ppm_v=EXCLUDED.largo_static_ppm_v,
  inclinacion_imu_deg=EXCLUDED.inclinacion_imu_deg,
  actualizacion_hz=EXCLUDED.actualizacion_hz,
  usb=EXCLUDED.usb,
  usb_c=EXCLUDED.usb_c,
  rs232=EXCLUDED.rs232,
  auditoria_fuente=EXCLUDED.auditoria_fuente,
  auditoria_notas=EXCLUDED.auditoria_notas;

INSERT INTO equipo_radio_frecuencia (
  id_equipo, frecuencia_min_mhz, frecuencia_max_mhz
) VALUES ('GNSS-SINOGNSS-T20', 410, 470)
ON CONFLICT (id_equipo, frecuencia_min_mhz, frecuencia_max_mhz) DO NOTHING;

COMMIT;
